$(document).ready(function(){
    $("#consentheader").click(function(){
        $('#consent').toggle();
    });
});
$(document).ready(function(){
    $("#consenQtheader").click(function(){
        $('#consentQ').toggle();
    });
});
$(document).ready(function(){
    $("#helptheader").click(function(){
        $('#help').toggle();
    });
});
$(document).ready(function(){
    $("anonymousheader").click(function(){
        $('#anonymous').toggle();
    });
});
$(document).ready(function(){
    $("talkheader").click(function(){
        $('#talk').toggle();
    });
});